version: '3'
services:
  filmes-db:
    image: tutum/mongodb
    container_name: filmes-db
    restart: always
    networks:
      - filmes
    environment:
      - AUTH=no
    ports:
      - '27017:27017'
      - '28017:28017'
  filmes-api:
    build: './'
    container_name: filmes-api
    ports:
      - 8080:8080
    networks:
      - filmes
    depends_on:
      - filmes-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_DB_HOST=filmes-db
      - MONGO_DB_PORT=27017
      - MONGO_DB_DATABASE=webflux
networks:
  filmes: